// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD65Vx0BiURrCYkGLz69w6EZEMpIHc5K7Y',
    appId: '1:811961094981:web:24491fc71939e83e20642c',
    messagingSenderId: '811961094981',
    projectId: 'casharooo-9584b',
    authDomain: 'casharooo-9584b.firebaseapp.com',
    storageBucket: 'casharooo-9584b.firebasestorage.app',
    measurementId: 'G-D3Z52KQ3HR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWIMA7ljFb_0X3WynLkF3NyzXe1LmOXDM',
    appId: '1:811961094981:android:7c2804c77277e91920642c',
    messagingSenderId: '811961094981',
    projectId: 'casharooo-9584b',
    storageBucket: 'casharooo-9584b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQpslYKdy73w-vHcU6o-S3LEnniUtXcXc',
    appId: '1:811961094981:ios:56dfa8ba6dd3b98f20642c',
    messagingSenderId: '811961094981',
    projectId: 'casharooo-9584b',
    storageBucket: 'casharooo-9584b.firebasestorage.app',
    iosClientId: '811961094981-opcas8kip1he8cipc7h868bfa69uj7po.apps.googleusercontent.com',
    iosBundleId: 'com.example.casharoo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQpslYKdy73w-vHcU6o-S3LEnniUtXcXc',
    appId: '1:811961094981:ios:56dfa8ba6dd3b98f20642c',
    messagingSenderId: '811961094981',
    projectId: 'casharooo-9584b',
    storageBucket: 'casharooo-9584b.firebasestorage.app',
    iosClientId: '811961094981-opcas8kip1he8cipc7h868bfa69uj7po.apps.googleusercontent.com',
    iosBundleId: 'com.example.casharoo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD65Vx0BiURrCYkGLz69w6EZEMpIHc5K7Y',
    appId: '1:811961094981:web:69472bc71467282a20642c',
    messagingSenderId: '811961094981',
    projectId: 'casharooo-9584b',
    authDomain: 'casharooo-9584b.firebaseapp.com',
    storageBucket: 'casharooo-9584b.firebasestorage.app',
    measurementId: 'G-YC67C31PDC',
  );
}
